### PR TITLE
Lib-No more-Secret

### PR DESCRIPTION
**Pull request by prateekmedia**
Taken for granted from https://github.com/flathub/com.github.vladimiry.ElectronMail/blob/711c28869d59e7b29faf07458a5dae8c468e4e47/com.github.vladimiry.ElectronMail.yaml

### CODE REVIEW

**Comment by prateekmedia** [comment]
@pieas-asif @TCROC  please check

**Comment by TCROC** [comment]
@prateekmedia still errors for me on pop os :/

image

Here are the logs.

```
flatpak run com.getmailspring.Mailspring
Gtk-Message: 11:07:13.774: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:07:13.775: Failed to load module "canberra-gtk-module"
[2:1219/110713.785763:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1219/110713.785814:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Running database migrations
App load time: 138ms

{"error":null}
[2:1219/110713.900287:ERROR:bus.cc(562)] Failed to get the ownership of org.kde.StatusNotifierItem-2-1: org.freedesktop.DBus.Error.ServiceUnknown
Manual update check (updates.getmailspring.com/check/linux/x64/1.13.2-8a0a82ea/anonymous/stable) returned 204
(electron) 'scroll-touch-{begin,end,edge}' are deprecated and will be removed. Please use the WebContents 'input-event' event instead.
```

The initial login works, but it doesn't save the login.  I get that error and have to re-login after opening the application.

**Comment by prateekmedia** [comment]
@TCROC was the errors before too or this PR caused it? Also can you click on Error Details and send here.

**Comment by TCROC** [comment]
I'll pull from the current release branch and check

**Comment by TCROC** [comment]
Here are the error details:

image

And the log with potentially sensitive info removed:

```
Mailspring Version: 1.13.2-8a0a82ea
Platform: linux
Account State: sync_error
Account Provider: gmail
IMAP Server: imap.gmail.com
SMTP Server: smtp.gmail.com
--------------------------------------------
289 [2023-12-19 11:07:05.664] [background] [info] - Fetching full headers for 6 (of 6 needed)
289 [2023-12-19 11:07:05.830] [background] [info] Cleaning local cache and updating stats
289 [2023-12-19 11:07:05.869] [background] [info] -- 1 message bodies deleted from local cache.
289 [2023-12-19 11:07:06.012] [background] [info] syncFolderUIDRange for [Gmail]/Trash, UIDs: 1 - 11704, Heavy: false
289 [2023-12-19 11:07:06.202] [background] [info] - [Gmail]/Trash: remote=0, local=0, remoteUID=<removed_id>
289 [2023-12-19 11:07:06.202] [background] [info] Cleaning local cache and updating stats
289 [2023-12-19 11:07:06.210] [background] [info] -- 0 message bodies deleted from local cache.
289 [2023-12-19 11:07:06.389] [background] [info] syncFolderUIDRange for [Gmail]/Spam, UIDs: 1 - 2064, Heavy: false
289 [2023-12-19 11:07:06.610] [background] [info] - [Gmail]/Spam: remote=7, local=7, remoteUID=<removed_id>
289 [2023-12-19 11:07:06.610] [background] [info] - Fetching full headers for 7 (of 7 needed)
289 [2023-12-19 11:07:07.019] [background] [info] - Updating message <removed_id>
289 [2023-12-19 11:07:07.019] [background] [info] -- Unread (true to false)
289 [2023-12-19 11:07:07.022] [background] [info] - Updating message <removed_id>
289 [2023-12-19 11:07:07.022] [background] [info] -- Unread (true to false)
289 [2023-12-19 11:07:07.027] [background] [info] - Updating message <removed_id>
289 [2023-12-19 11:07:07.027] [background] [info] -- Unread (true to false)
289 [2023-12-19 11:07:07.031] [background] [info] - Updating message <removed_id>
289 [2023-12-19 11:07:07.031] [background] [info] -- Unread (true to false)
289 [2023-12-19 11:07:07.034] [background] [info] - Updating message <removed_id>
289 [2023-12-19 11:07:07.034] [background] [info] -- Unread (true to false)
289 [2023-12-19 11:07:07.038] [background] [info] - Updating message <removed_id>
289 [2023-12-19 11:07:07.038] [background] [info] -- Unread (true to false)
289 [2023-12-19 11:07:07.041] [background] [info] - Updating message <removed_id>
289 [2023-12-19 11:07:07.041] [background] [info] -- Unread (true to false)
289 [2023-12-19 11:07:07.045] [background] [info] Cleaning local cache and updating stats
289 [2023-12-19 11:07:07.058] [background] [info] -- 0 message bodies deleted from local cache.
289 [2023-12-19 11:07:07.069] [background] [info] Sync loop deleting unlinked messages with phase 2.
289 [2023-12-19 11:07:07.076] [background] [info] Sync loop complete.
289 [2023-12-19 11:07:13.656] [metadataExpiration] [info] Scanning for expired metadata
289 [2023-12-19 11:07:13.656] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
```

And similar logs in the terminal at startup:

```
flatpak run com.getmailspring.Mailspring
Gtk-Message: 11:19:11.125: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:19:11.125: Failed to load module "canberra-gtk-module"
[2:1219/111911.136036:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1219/111911.136073:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Running database migrations
App load time: 138ms

{"error":null}
[2:1219/111911.254137:ERROR:bus.cc(562)] Failed to get the ownership of org.kde.StatusNotifierItem-2-1: org.freedesktop.DBus.Error.ServiceUnknown
Manual update check (updates.getmailspring.com/check/linux/x64/1.13.2-8a0a82ea/anonymous/stable) returned 204
```

I'll see what it logs when I log in:

```
flatpak run com.getmailspring.Mailspring
Gtk-Message: 11:19:11.125: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:19:11.125: Failed to load module "canberra-gtk-module"
[2:1219/111911.136036:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1219/111911.136073:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Running database migrations
App load time: 138ms

{"error":null}
[2:1219/111911.254137:ERROR:bus.cc(562)] Failed to get the ownership of org.kde.StatusNotifierItem-2-1: org.freedesktop.DBus.Error.ServiceUnknown
Manual update check (updates.getmailspring.com/check/linux/x64/1.13.2-8a0a82ea/anonymous/stable) returned 204
[50:1219/112122.126885:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[50:1219/112122.130390:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[50:1219/112122.144114:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

Looks like gl_surface_presentation errors get logged after doing that.

NOTE: Mailspring worked prior to the 1.13.1 update.  I'm pretty sure the keychain update broke it for flathub.

**Comment by prateekmedia** [comment]
Weird cause the last manual update to code was before 1.12.0 and if it worked then there is nothing other than version is updated in code in 1.13.1 and 1.13.2

**Comment by TCROC** [comment]
It didn't work in 1.13.1 for me either. I just stopped using it and waited for 1.13.2 since they said a fix was going in for snap (same error). But it didn't fix it for flathub.

**Comment by TCROC** [comment]
Last working version I believe was 1.12. I can bisect and test tho to find the exact version after my lunch

**Comment by pieas-asif** [comment]
Hello @prateekmedia, I am still facing the same issue. And the error log is same as @TCROC [error](https://github.com/flathub/com.getmailspring.Mailspring/pull/35#issuecomment-1863082808).

**Comment by prateekmedia** [comment]
@pieas-asif Also were you also facing same error in the main version available on flatpak or only in this PR?

**Comment by TCROC** [comment]
Got back from lunch and tested things out.  The 1.13.1 update broke Mailspring on flathub.  I confirmed by running this command:

```
flatpak remote-info --log flathub com.getmailspring.Mailspring
```

I got an output of:

```
        ID: com.getmailspring.Mailspring
       Ref: app/com.getmailspring.Mailspring/x86_64/stable
      Arch: x86_64
    Branch: stable
Collection: org.flathub.Stable
  Download: 157.5 MB
 Installed: 418.8 MB
   Runtime: org.freedesktop.Platform/x86_64/23.08
       Sdk: org.freedesktop.Sdk/x86_64/23.08

    Commit: 2bbfa746a0eaac979a450c8acfb48960220c0f90d492faf7499fed74e53d4c24
    Parent: e4e099bd840a9cacc61cc0bf49ee6df1035e78b091e3941274091ccee06cdd0a
   Subject: Update mailspring.deb to 1.13.2 (#33) (18d8c058)
      Date: 2023-12-18 19:21:07 +0000
   History: 

    Commit: e4e099bd840a9cacc61cc0bf49ee6df1035e78b091e3941274091ccee06cdd0a
   Subject: Update mailspring.deb to 1.13.1 (#32) (398373af)
      Date: 2023-11-22 12:36:31 +0000

    Commit: 6ce5baf3746c4a25a714da6cf2f8926b464220441f31ee95c5b0823a55d89baf
   Subject: fix: bump base to 23.08 (#29) (45d11cdb)
      Date: 2023-10-04 17:56:50 +0000

    Commit: e1418af4828f12522f04570895366983c14c04d2be1ce21f1ce6dbcf26e5cba1
   Subject: fix: #24 ig (#26) (54da4280)
      Date: 2023-07-30 08:07:43 +0000

    Commit: 1efcb0434736d5248718166ed235b551bc6b513d14163b61950abf8213a5a894
   Subject: Update mailspring.deb to 1.10.7 (#19) (3c29fbc3)
      Date: 2022-12-03 16:34:48 +0000

    Commit: 600cc0d3eaa2d41bc4395dd51aee67385bf6c0f0108100be77a6a56321c0a776
   Subject: Update mailspring.deb to 1.10.7 (#19) (3c29fbc3)
      Date: 2022-12-03 16:34:48 +0000

    Commit: eb1c4be00e177237bc8afef6f120b9fc958aef5920f2b904d92db2bcedb974f3
   Subject: Update mailspring.deb to 1.10.5 (c792362a)
      Date: 2022-08-11 03:15:57 +0000

    Commit: b1af3cdbd45fe2d80c7d6bf37858a9e5dd7181d9af092e38c5894ca2d4cc693e
   Subject: Update mailspring.deb to 1.10.4 (75e0e67a)
      Date: 2022-08-09 16:26:53 +0000

    Commit: 2c574f1eb1709ac71ba31613b8e54a6557d7462c4126296cbe0b7b3a1410401e
   Subject: Update mailspring.deb to 1.10.3 (7f82b16c)
      Date: 2022-04-18 15:19:26 +0000

    Commit: b53e5bf3db6ac1809a27f3d25210a7481c91d8a71893f148a11f4ddc2d1a5c32
   Subject: Update mailspring.deb to 1.10.2 (40b73424)
      Date: 2022-04-14 09:50:13 +0000
```

I tested the top 3 commits and these were the results:

1.13.2 = broken ❌ 
1.13.1 = broken ❌ 
 23.08 = works  ✅ 
 
 So the flathub breaking bug was introduced in 1.13.1 and the snap patch for 1.13.2 did not fix it.

**Comment by TCROC** [comment]
And one fascinating thing to note:

When updating from the broken one to the fixed one, you actually have to quit and reopen mailspring twice in order for the accounts to start working again.  At least for the UI to say that the accounts are working (it might just be a UI cache).

**Comment by marchermans** [comment]
I am also running into this.
Even with FlatSeal permissions added, it seems like the Flatpak version is looking for the keyring which it then can not find.

Running it from the command line gets me this log: https://gist.github.com/marchermans/dc9a7ea93999d6add8aaf934b2b7f3d1

**Pull request closed without merging**
